/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package sanitize

import (
	"testing"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/yaml"
)

// The corpus proves each exclusion rule fires. These prove the rules do NOT fire on their
// near-misses — the more dangerous direction by far. A rule that wrongly keeps an object
// wastes a little space; a rule that wrongly drops one is silent data loss discovered at
// restore time, when it is too late to go back and capture it.

func parseObj(t *testing.T, s string) *unstructured.Unstructured {
	t.Helper()
	obj := &unstructured.Unstructured{}
	if err := yaml.Unmarshal([]byte(s), &obj.Object); err != nil {
		t.Fatalf("parse: %v", err)
	}
	return obj
}

func TestExclusionNearMissesAreKept(t *testing.T) {
	for name, tc := range map[string]struct {
		doc string
		ctx ExcludeContext
	}{
		// E1 keeps naked Pods: nothing will recreate them, so they ARE the desired state.
		"naked pod": {doc: `
apiVersion: v1
kind: Pod
metadata:
  name: standalone
spec:
  containers: [{name: app, image: alpine}]
`},
		// An ownerReference that is not the controller (controller: false, or absent) does not
		// mean anything will recreate the object.
		"pod with a non-controller owner": {doc: `
apiVersion: v1
kind: Pod
metadata:
  name: adopted
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: owner
    uid: "1"
    controller: false
spec:
  containers: [{name: app, image: alpine}]
`},
		"pod with an owner that omits controller": {doc: `
apiVersion: v1
kind: Pod
metadata:
  name: adopted2
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: owner
    uid: "1"
spec:
  containers: [{name: app, image: alpine}]
`},
		// E2 is specifically "owned by a Deployment". A ReplicaSet owned by something else is
		// not going to be regenerated by a Deployment spec.
		"replicaset owned by a custom controller": {doc: `
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
  ownerReferences:
  - apiVersion: example.com/v1
    kind: Fleet
    name: fleet
    uid: "1"
    controller: true
spec: {replicas: 1}
`},
		"standalone replicaset": {doc: `
apiVersion: apps/v1
kind: ReplicaSet
metadata: {name: rs-standalone}
spec: {replicas: 1}
`},
		// Same reasoning for E3.
		"job owned by a custom controller": {doc: `
apiVersion: batch/v1
kind: Job
metadata:
  name: job
  ownerReferences:
  - apiVersion: example.com/v1
    kind: Pipeline
    name: p
    uid: "1"
    controller: true
spec: {}
`},
		"standalone job": {doc: "apiVersion: batch/v1\nkind: Job\nmetadata: {name: oneshot}\nspec: {}\n"},
		// E7 is scoped to the service-account-token type; every other Secret is user data and
		// is exactly what a namespace recovery needs.
		"opaque secret": {doc: `
apiVersion: v1
kind: Secret
metadata: {name: db-creds}
type: Opaque
data: {password: c2VjcmV0}
`},
		"tls secret": {doc: `
apiVersion: v1
kind: Secret
metadata: {name: web-tls}
type: kubernetes.io/tls
`},
		"helm release secret": {doc: `
apiVersion: v1
kind: Secret
metadata: {name: sh.helm.release.v1.web.v3}
type: helm.sh/release.v1
`},
		// E10 drops run records only. Schedules and locations are user configuration and are
		// explicitly kept (04-manifest-backup.md §2.2).
		"backupschedule is configuration": {doc: `
apiVersion: crystalbackup.io/v1alpha1
kind: BackupSchedule
metadata: {name: nightly}
spec: {}
`},
		"backuplocation is configuration": {doc: `
apiVersion: crystalbackup.io/v1alpha1
kind: BackupLocation
metadata: {name: my-bucket}
spec: {}
`},
		// E11 is one specific ConfigMap name.
		"ordinary configmap": {doc: "apiVersion: v1\nkind: ConfigMap\nmetadata: {name: app-config}\n"},
		// E4: a hand-managed EndpointSlice carries no control-plane managed-by label.
		"unmanaged endpointslice": {doc: `
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: manual
  labels: {endpointslice.kubernetes.io/managed-by: my-operator}
addressType: IPv4
`},
		// E4: Endpoints for a SELECTORLESS Service are the only record of those addresses.
		"endpoints for a selectorless service": {
			doc: "apiVersion: v1\nkind: Endpoints\nmetadata: {name: external-api}\n",
			ctx: ExcludeContext{ServicesWithSelector: map[string]bool{"web": true}},
		},
		// E5 is scoped to Event; a CRD named Event from another group is someone's data.
		"event-like custom resource": {doc: `
apiVersion: example.com/v1
kind: Event
metadata: {name: business-event}
`},
		// E8 keeps the Certificate itself — it is what reissues the transients.
		"certificate is kept": {doc: `
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: {name: web-tls}
spec: {}
`},
	} {
		t.Run(name, func(t *testing.T) {
			obj := parseObj(t, tc.doc)
			if excluded, rule := ShouldExclude(obj, tc.ctx); excluded {
				t.Errorf("object was excluded by %s but must be kept — wrongly dropping it is silent data loss", rule)
			}
		})
	}
}

// The http01-solver label marks transient objects of several kinds at once, so it has to be
// checked before any per-kind branch claims them.
func TestHTTP01SolverLabelExcludesAnyKind(t *testing.T) {
	for _, doc := range []string{
		"apiVersion: v1\nkind: Pod\nmetadata: {name: cm-acme-http-solver-x, labels: {acme.cert-manager.io/http01-solver: \"true\"}}\n",
		"apiVersion: v1\nkind: Service\nmetadata: {name: cm-acme-http-solver-y, labels: {acme.cert-manager.io/http01-solver: \"true\"}}\n",
		"apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata: {name: cm-acme-http-solver-z, labels: {acme.cert-manager.io/http01-solver: \"true\"}}\n",
	} {
		obj := parseObj(t, doc)
		excluded, rule := ShouldExclude(obj, ExcludeContext{})
		if !excluded || rule != ExcludeCertManagerTransient {
			t.Errorf("%s: got (%v, %q), want (true, %q)", obj.GetKind(), excluded, rule, ExcludeCertManagerTransient)
		}
	}
}

func TestExcludeNilObject(t *testing.T) {
	if excluded, _ := ShouldExclude(nil, ExcludeContext{}); excluded {
		t.Error("a nil object should not be reported as excluded")
	}
}

func TestExcludeCertManagerKinds(t *testing.T) {
	for doc, want := range map[string]bool{
		"apiVersion: acme.cert-manager.io/v1\nkind: Challenge\nmetadata: {name: c}\n":      true,
		"apiVersion: cert-manager.io/v1\nkind: CertificateRequest\nmetadata: {name: cr}\n": true,
		"apiVersion: cert-manager.io/v1\nkind: Issuer\nmetadata: {name: i}\n":              false,
		"apiVersion: acme.cert-manager.io/v1\nkind: SomethingElse\nmetadata: {name: s}\n":  false,
	} {
		obj := parseObj(t, doc)
		if excluded, _ := ShouldExclude(obj, ExcludeContext{}); excluded != want {
			t.Errorf("%s/%s: excluded = %v, want %v", obj.GetAPIVersion(), obj.GetKind(), excluded, want)
		}
	}
}

func TestExcludeEventInBothGroups(t *testing.T) {
	for _, doc := range []string{
		"apiVersion: v1\nkind: Event\nmetadata: {name: e1}\n",
		"apiVersion: events.k8s.io/v1\nkind: Event\nmetadata: {name: e2}\n",
	} {
		if excluded, rule := ShouldExclude(parseObj(t, doc), ExcludeContext{}); !excluded || rule != ExcludeEvent {
			t.Errorf("%s: got (%v, %q)", doc, excluded, rule)
		}
	}
}
