/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package mover

import (
	"fmt"
	"strings"

	corev1 "k8s.io/api/core/v1"
)

// ProfilesDocFile is where RenderProfilesDoc's output is committed, relative to the repository
// root. `make mover-profiles` writes it; `make mover-profiles-verify` fails when it is stale.
const ProfilesDocFile = "docs/MOVER-RESOURCES.md"

// RenderProfilesDoc renders the operator-facing reference for mover sizing FROM the built-in
// table, so the documented numbers cannot drift from the running ones: there is no second copy to
// update, only a file to regenerate.
func RenderProfilesDoc() []byte {
	var b strings.Builder

	b.WriteString("<!-- GENERATED by `make mover-profiles` from internal/mover/profiles.go. DO NOT EDIT. -->\n\n")
	b.WriteString("# Mover resources\n\n")
	b.WriteString(profilesDocIntro)

	b.WriteString("## The built-in table\n\n")
	b.WriteString("| operation | class | cpu request | memory request | cpu limit | memory limit | restic cache cap |\n")
	b.WriteString("|---|---|---|---|---|---|---|\n")
	for _, op := range Operations() {
		spec := builtinSpecs[op]
		profile := Profiles(nil).For(op)
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n",
			op, spec.class,
			docQuantity(profile.Requests, corev1.ResourceCPU),
			docQuantity(profile.Requests, corev1.ResourceMemory),
			docQuantity(profile.Limits, corev1.ResourceCPU),
			docQuantity(profile.Limits, corev1.ResourceMemory),
			docCache(profile),
		)
	}

	b.WriteString(profilesDocBody)
	return []byte(b.String())
}

// docCache renders the cache cap cell, spelling out the unbounded case rather than leaving a dash
// a reader could take for "not applicable".
func docCache(p Profile) string {
	if p.CacheSizeLimit == nil {
		return "unbounded"
	}
	return "`" + p.CacheSizeLimit.String() + "`"
}

// docQuantity renders one cell, with an em dash for a field the pod does not carry at all.
func docQuantity(list corev1.ResourceList, name corev1.ResourceName) string {
	q, ok := list[name]
	if !ok {
		return "—"
	}
	return "`" + q.String() + "`"
}

const profilesDocIntro = `Every mover Job — backup, restore, prune, check, sync, the manifest
shapes — runs with requests, limits and a bounded restic cache chosen **per operation**. Before
0.6.1 they all ran with nothing at all: no requests (so every mover pod was BestEffort, first in
line to be evicted under node pressure) and an unbounded cache emptyDir on the kubelet's disk.

These numbers are **not** benchmark output. The millions-of-files load test that would produce the
real curves is a separate, still-undelivered roadmap item; what is here is a set of deliberate,
conservative ceilings whose purpose is to stop one mover taking a node down, plus a scheduling
floor. Raise them for your workload — that is what the knob is for — and do not read them as a
statement about what restic needs.

`

const profilesDocBody = `
### Why the classes differ

| class | operations | shape |
|---|---|---|
| ` + "`data`" + ` | ` + "`backup`, `restore`" + ` | streams a PVC through restic: CPU for chunking/compression/encryption, memory for the index held while doing it |
| ` + "`repo-heavy`" + ` | ` + "`prune`, `check`, `sync`" + ` | repository-wide work whose cost tracks the repository, not the volume: prune rewrites packs holding the whole index, check re-reads the structure, sync opens two repositories at once |
| ` + "`repo-light`" + ` | ` + "`init`, `forget`, `snapshots`, `unlock`" + ` | index/metadata only; never touches pack data |
| ` + "`manifests`" + ` | the four manifest shapes | a few MB of YAML plus a client-go object cache for one namespace (or one cluster's CRDs and RBAC) |

**CPU limits are unset on purpose.** CPU is compressible: a mover wanting more than its share is
throttled by scheduler shares, whereas a hard CPU limit on a backup buys nothing but a backup that
no longer finishes inside its window. Set ` + "`limits.cpu`" + ` per operation if your platform
requires one.

### The two failures this configuration can cause, and what they look like

Both of them kill the mover before it can report anything of its own, and before 0.6.1 both
arrived on the CR as ` + "`MoverCrashed`" + ` — the operator's own sizing, diagnosed as a bug in
the mover. They are now told apart and named:

| status reason | what happened | what to do |
|---|---|---|
| ` + "`MoverOOMKilled`" + ` | the container exceeded ` + "`limits.memory`" + ` | raise that operation's memory limit |
| ` + "`MoverEvicted: …`" + ` | the restic cache emptyDir exceeded ` + "`cacheSizeLimit`" + ` (or the node ran out of disk). The kubelet's own message is quoted verbatim and names the volume and the number | raise that operation's ` + "`cacheSizeLimit`" + `, or set it to ` + "`\"0\"`" + ` for an unbounded cache |

An eviction is **not** an error restic sees. There is no ENOSPC and no failed write: the kubelet's
eviction manager polls, notices the volume is over its cap, and removes the pod seconds later. A
cap set too low therefore turns a working backup into a pod that disappears mid-run — which is why
the default is a ceiling far above any expected cache rather than a fitted estimate, and why the
Backup's status now says which of the two it was.

The restic cache is **cold on every run**: each mover pod gets a fresh emptyDir, so the cap bounds
what ONE operation downloads (index, snapshots, the tree blobs it walks), not an accumulation.
The ` + "`/tmp`" + ` and manifest-scratch emptyDirs are deliberately left unbounded — restic
assembles one pack file at a time there, and a second eviction trigger for tens of MB would be all
risk and no gain.

### Overriding

` + "```yaml" + `
# values.yaml
mover:
  profiles:
    default:            # applied to every operation first
      requests:
        cpu: 100m
    prune:              # then the operation's own entry
      limits:
        memory: 16Gi
      cacheSizeLimit: 60Gi
` + "```" + `

Merging is **field by field**: the example above raises prune's memory limit and cache cap and
leaves prune's CPU request — and every other operation — exactly as the table above has them.

` + "`\"0\"`" + ` removes a field rather than setting it to zero: ` + "`cacheSizeLimit: \"0\"`" + `
is an unbounded cache, ` + "`limits: {memory: \"0\"}`" + ` is an unlimited container.

The chart renders these overrides into a ConfigMap and the operator reads it **once, at startup**
(the deployment carries a checksum of it, so ` + "`helm upgrade`" + ` restarts the pod). A file
that names an unknown operation, uses an unknown field, carries an unparseable quantity or asks
for a request above its own limit **stops the operator** — an override that is ignored silently is
worse than one that is refused loudly. The effective table is logged at startup, one line per
operation.
`
