# shellcheck shell=bash
# Source me — never execute: `source scripts/load-env.sh`
#
# Exports the credentials the crucible needs from the repo's .secrets/ dir
# (git-ignored; see secrets.example/ for the expected layout):
#
#   HETZNER_TOKEN        raw Hetzner Cloud API token   -> HCLOUD_TOKEN
#   HETZNER_S3           ACCESS_TOKEN= / SECRET_KEY=   -> AWS_* + TF_VAR_s3_*
#   crystalbackup.key    SSH private key               -> ANSIBLE_PRIVATE_KEY_FILE
#
# Also sources artifacts/crucible.env (non-secret facts written by terraform:
# S3_BUCKET, S3_ENDPOINT, MASTER1_PUBLIC_IP).
#
# Values are exported into the environment only — never written to disk,
# never echoed.

# Resolve this file's own path under BOTH bash and zsh. The crucible's tooling
# sources this from bash, but a human may source it from a zsh prompt — where
# ${BASH_SOURCE} is unset, so the old math walked one dir too high. `eval` hides
# zsh's %x syntax from bash's parser.
if [ -n "${ZSH_VERSION:-}" ]; then
  eval '_crucible_self="${(%):-%x}"'
elif [ -n "${BASH_SOURCE:-}" ]; then
  _crucible_self="${BASH_SOURCE[0]}"
else
  _crucible_self="${0}"
fi

_crucible_dir="$(cd "$(dirname "${_crucible_self}")/.." && pwd)"
_repo_root="$(cd "${_crucible_dir}/../.." && pwd)"
_secrets_dir="${CRYSTALBACKUP_SECRETS_DIR:-${_repo_root}/.secrets}"

if [[ ! -d "${_secrets_dir}" ]]; then
  echo "load-env: WARNING — no secrets dir at ${_secrets_dir} (see test/crucible/secrets.example/)" >&2
fi

if [[ -f "${_secrets_dir}/HETZNER_TOKEN" ]]; then
  HCLOUD_TOKEN="$(tr -d '[:space:]' < "${_secrets_dir}/HETZNER_TOKEN")"
  export HCLOUD_TOKEN
fi

if [[ -f "${_secrets_dir}/HETZNER_S3" ]]; then
  ACCESS_TOKEN="" SECRET_KEY=""
  # shellcheck disable=SC1091
  source "${_secrets_dir}/HETZNER_S3"
  export AWS_ACCESS_KEY_ID="${ACCESS_TOKEN}"
  export AWS_SECRET_ACCESS_KEY="${SECRET_KEY}"
  export TF_VAR_s3_access_key="${ACCESS_TOKEN}"
  export TF_VAR_s3_secret_key="${SECRET_KEY}"
  unset ACCESS_TOKEN SECRET_KEY
fi

if [[ -f "${_secrets_dir}/crystalbackup.key" ]]; then
  export ANSIBLE_PRIVATE_KEY_FILE="${_secrets_dir}/crystalbackup.key"
fi

# Non-secret facts generated by `mise run infra` (safe to source, git-ignored).
if [[ -f "${_crucible_dir}/artifacts/crucible.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${_crucible_dir}/artifacts/crucible.env"
  set +a
fi

unset _crucible_dir _repo_root _secrets_dir _crucible_self
