# This rule is not used by the project bs-k8s-backup itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the crystalbackup.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bs-k8s-backup
    app.kubernetes.io/managed-by: kustomize
  name: clustererasure-editor-role
rules:
- apiGroups:
  - crystalbackup.io
  resources:
  - clustererasures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crystalbackup.io
  resources:
  - clustererasures/status
  verbs:
  - get
