---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crystalbackup.io
  resources:
  - backuprepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crystalbackup.io
  resources:
  - backuprepositories/finalizers
  - clusterbackuplocations/finalizers
  verbs:
  - update
- apiGroups:
  - crystalbackup.io
  resources:
  - backuprepositories/status
  - clusterbackuplocations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crystalbackup.io
  resources:
  - clusterbackuplocations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
