# ---------------------------------------------------------------------------
# Glue: generated ansible inventory + env file for the test suite.
# Both land in git-ignored locations (the inventory carries the RKE2 token).
# ---------------------------------------------------------------------------

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/hosts.ini"
  file_permission = "0600"

  content = templatefile("${path.module}/templates/hosts.ini.tftpl", {
    # private_mac lets the `common` role bring the private NIC up by MAC when
    # cloud-init raced the network attach and never wrote a netplan entry for it
    # (one(...) asserts the single inline network block — fails loudly if that
    # ever changes). Hetzner's DHCP hands the reserved IP to this MAC.
    masters = [for i, s in hcloud_server.master : {
      name        = s.name
      public_ip   = s.ipv4_address
      private_ip  = local.master_ips[i]
      private_mac = one(s.network).mac_address
    }]
    workers = [for i, s in hcloud_server.worker : {
      name        = s.name
      public_ip   = s.ipv4_address
      private_ip  = local.worker_ips[i]
      private_mac = one(s.network).mac_address
    }]
    rke2_token   = random_password.rke2_token.result
    rke2_channel = var.rke2_channel
    rke2_version = var.rke2_version
  })
}

# Non-secret facts consumed by `make test` / the Ginkgo suite.
resource "local_file" "crucible_env" {
  filename        = "${path.module}/../artifacts/crucible.env"
  file_permission = "0644"

  content = <<-EOT
    # Generated by terraform — non-secret crucible facts (safe to source).
    S3_BUCKET=${local.bucket_name}
    S3_ENDPOINT=https://${var.s3_endpoint}
    S3_REGION=${var.s3_region}
    MASTER1_PUBLIC_IP=${hcloud_server.master[0].ipv4_address}
  EOT
}
