# ---------------------------------------------------------------------------
# Glue: generated ansible inventory + env file for the test suite.
# Both land in git-ignored locations (the inventory carries the RKE2 token).
# ---------------------------------------------------------------------------

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/hosts.ini"
  file_permission = "0600"

  content = templatefile("${path.module}/templates/hosts.ini.tftpl", {
    masters = [for i, s in hcloud_server.master : {
      name       = s.name
      public_ip  = s.ipv4_address
      private_ip = local.master_ips[i]
    }]
    workers = [for i, s in hcloud_server.worker : {
      name       = s.name
      public_ip  = s.ipv4_address
      private_ip = local.worker_ips[i]
    }]
    rke2_token   = random_password.rke2_token.result
    rke2_channel = var.rke2_channel
    rke2_version = var.rke2_version
  })
}

# Non-secret facts consumed by `make test` / the Ginkgo suite.
resource "local_file" "crucible_env" {
  filename        = "${path.module}/../artifacts/crucible.env"
  file_permission = "0644"

  content = <<-EOT
    # Generated by terraform — non-secret crucible facts (safe to source).
    S3_BUCKET=${minio_s3_bucket.backup_target.bucket}
    S3_ENDPOINT=https://${var.s3_endpoint}
    S3_REGION=${var.s3_region}
    MASTER1_PUBLIC_IP=${hcloud_server.master[0].ipv4_address}
  EOT
}
