apiVersion: crystalbackup.io/v1alpha1
kind: ClusterRestore
metadata:
  labels:
    app.kubernetes.io/name: bs-k8s-backup
    app.kubernetes.io/managed-by: kustomize
  name: clusterrestore-sample
spec:
  # TODO(user): Add fields here
